// <auto-generated />
using Advertising.Dal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertisingService.Migrations.AdvertisingService
{
    [DbContext(typeof(AdvertisingServiceContext))]
    [Migration("20190912080823_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Entity.AdvertisingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AdvertisingCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Недвижимость"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Авто и транспорт"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Техника"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Мода и стиль"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Всё для дома"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Ремонт и стройка"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Сад и огород"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Хобби, спорт и туризм"
                        });
                });

            modelBuilder.Entity("Common.Entity.AdvertisingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisingCategoryId");

                    b.Property<string>("AdvertisingName")
                        .IsRequired();

                    b.Property<string>("ImagePath");

                    b.Property<string>("ItemPrice");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Advertisings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertisingCategoryId = 1,
                            AdvertisingName = "Сдам квартиру 1 комнатную",
                            ImagePath = "https://www.pufikhomes.com/wp-content/uploads/2018/11/smart-small-white-apartment-in-sweden-32sqm-pufikhomes-1.jpg",
                            ItemPrice = "Договорная",
                            Text = "Сдам 1 комнатную квартиру 100м2 на длительный срок, за подробностями обращаться по телефону +12345678945"
                        },
                        new
                        {
                            Id = 2,
                            AdvertisingCategoryId = 1,
                            AdvertisingName = "Продам гараж",
                            ImagePath = "https://garage.abw.by/assets/gallery_thumbnails/c9/c91d8e781c2e514dc7c747f9c6cee4d5.jpg",
                            ItemPrice = "5000 р.",
                            Text = "Продам гараж, ул. Терёхина, по вопросам звонить +1234567890978"
                        },
                        new
                        {
                            Id = 3,
                            AdvertisingCategoryId = 2,
                            AdvertisingName = "Колпаки R15 Opel",
                            ImagePath = "https://images.by.prom.st/144841415_w640_h640_kolpak-kolesnyj-r15.jpg",
                            ItemPrice = "60",
                            Text = "Продам набор колпаков 4 шт. +1234567890978"
                        },
                        new
                        {
                            Id = 4,
                            AdvertisingCategoryId = 2,
                            AdvertisingName = "Прицеп бортовой легковой ССT 7132-08",
                            ImagePath = "http://images.slanet.by/~src8356904/Pricep_bortovoj_legkovoj_SST-7132-08_K.jpg",
                            ItemPrice = "1750 р.",
                            Text = "Прицеп новый. Полностью оцинкованный кузов.Подвеска рессоры+амортизаторы. Обращаться +12345678945"
                        },
                        new
                        {
                            Id = 5,
                            AdvertisingCategoryId = 3,
                            AdvertisingName = "Смартфон Redmi Note 7 3/32",
                            ImagePath = "https://img.letgo.com/images/9e/6a/f4/7b/9e6af47b14f096302b59d17826a094be.jpeg?impolicy=img_600",
                            ItemPrice = "430 р.",
                            Text = "Продаю за ненадобностью, так как подвернулся телефон получше, а сам телефон без царапин, использовался недолго звонить +127498236598"
                        },
                        new
                        {
                            Id = 6,
                            AdvertisingCategoryId = 3,
                            AdvertisingName = "Наушники Plantronics RIG 600",
                            ImagePath = "https://img.mvideo.ru/Pdb/50049239b.jpg",
                            ItemPrice = "140 р.",
                            Text = "Звук отличный, микрофон съемный на 5, уши не устают, легкие, провод длинный. Стоит отметить отличное качество материалов, емкое звучание и шумоизоляцию. +4638764862934"
                        },
                        new
                        {
                            Id = 7,
                            AdvertisingCategoryId = 4,
                            AdvertisingName = "Часы мужские Tissot S9009",
                            ImagePath = "https://images.by.prom.st/108330101_chasy-muzhskie-tissot.jpg",
                            ItemPrice = "Договорная",
                            Text = "Продам срочно +823692863596"
                        },
                        new
                        {
                            Id = 8,
                            AdvertisingCategoryId = 4,
                            AdvertisingName = "Серебряное кольцо с живописью",
                            ImagePath = "https://i.pinimg.com/originals/b3/4d/d2/b34dd21927a6652f77bba24be7b66931.jpg",
                            ItemPrice = "Договорная",
                            Text = "Серебряное кольцо с живописью, собственного производства +473289472394"
                        },
                        new
                        {
                            Id = 9,
                            AdvertisingCategoryId = 5,
                            AdvertisingName = "Ванильная орхидея (ваниль)",
                            ImagePath = "http://cvetochki.net/sites/default/files/u736/orh1.jpg",
                            ItemPrice = "15 р.",
                            Text = "Ее нежные цветочки могут быть окрашены в желтый, белоснежный либо светло-зеленый цвет. +71382946127"
                        },
                        new
                        {
                            Id = 10,
                            AdvertisingCategoryId = 5,
                            AdvertisingName = "Диван-кровать",
                            ImagePath = "https://www.ikea.com/ru/ru/images/products/gessberg-divan-krovat-mestnyj-bezevyj__0532403_PE648047_S4.JPG",
                            ItemPrice = "150 р.",
                            Text = "Продам новый диван-кровать, так как не подошел по размерам, а возможности вернуть нет +124534645745"
                        },
                        new
                        {
                            Id = 11,
                            AdvertisingCategoryId = 6,
                            AdvertisingName = "Цемент М-400",
                            ImagePath = "https://angio.com.ua/files/angio/reg_images/m-400_2.jpg",
                            ItemPrice = "12 р.",
                            Text = "После ремонта осталось 3 мешка 25 кг +425673542734"
                        },
                        new
                        {
                            Id = 12,
                            AdvertisingCategoryId = 6,
                            AdvertisingName = "Продам краску",
                            ImagePath = "https://aura.if.ua/image/cache/catalog/tovary/kraski/tovar/chast1/luxpro9tr-500x500.jpg",
                            ItemPrice = "120",
                            Text = "Продам краску, цвет не того тона +4623756237564"
                        },
                        new
                        {
                            Id = 13,
                            AdvertisingCategoryId = 7,
                            AdvertisingName = "Корзина",
                            ImagePath = "https://content.kufar.by/gallery/34/3461009376.jpg",
                            ItemPrice = "15 р.",
                            Text = "Отличная корзина для сбора урожая, лёгкая, удобная. +758345783465"
                        },
                        new
                        {
                            Id = 14,
                            AdvertisingCategoryId = 7,
                            AdvertisingName = "Дрова",
                            ImagePath = "https://content.kufar.by/gallery/41/4126985343.jpg",
                            ItemPrice = "Договорная",
                            Text = "Дрова ель-сосна, береза-осина, дуб, можно смешанные,Колотые и чурками с доставкой 5 кубов (навал в кузове 6,5кубов). +472836576564"
                        },
                        new
                        {
                            Id = 15,
                            AdvertisingCategoryId = 8,
                            AdvertisingName = "Серия книг « Песнь льда и пламени»",
                            ImagePath = "https://content.kufar.by/gallery/34/3430032145.jpg",
                            ItemPrice = "70 р.",
                            Text = "Набор из четырех книг в отличном состоянии. +47287365723"
                        },
                        new
                        {
                            Id = 16,
                            AdvertisingCategoryId = 8,
                            AdvertisingName = "Нож Ganzo Firebird FH21",
                            ImagePath = "https://content.kufar.by/gallery/38/3833302936.jpg",
                            ItemPrice = "80 р.",
                            Text = "Сталь D2 (твердость 60 ед HRC) флиппер на подшипниках,рукоять из G10 +47236482634623"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
